apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
      - name: shoppingapi
        image: shoppingacr28394.azurecr.io/shoppingapi:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.3"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DatabaseSettings__ConnectionString
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: connection_string
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  selector:
    app: shoppingapi
  ports:
  - protocol: TCP
    port: 8080