services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
      #      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - shopping.db

    ports:
      - "8000:8080"

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings__ShoppingAPIUrl=http://shoppingapi:8080/"
#      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - shopping.db
      - shopping.api
    ports:
      - "8001:8080"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

